### PR TITLE
change data dirs to be relative to dataset file

### PR DESCRIPTION
**Pull request by akarshkumar0101**
This PR allows the ContactPose directory to be symlinked into any additional code base and hold the data directory elsewhere.
It finds the data directory relative to the dataset.py file (like it should be) rather than the additional code base directory.

### CODE REVIEW

**Comment by samarth-robo** [comment]
hi @akarshkumar0101, the data path `Contactpose/data/contactpose_data` is used at many locations in the codebase, with the rationale that if the data lives at any other location, it can be symlinked to that path. Can you please give an example where this does not work?

**Comment by akarshkumar0101** [comment]
We do symlink it to that exact path.

The existing code only works if running scripts from inside ContactPose directory.
Our proposed change lets the code be run from anywhere, because the path is described relative to the file dataset.py, rather than relative to where we run the script from.

**Comment by akarshkumar0101** [comment]
Done!

**Comment by samarth-robo** [comment]
@akarshkumar0101 one more thing. The `master` branch has moved ahead since you made your PR. So now the upstream needs to be merged to this PR before this PR can be merged. Can you either [give me permissions](git@github.com:facebookresearch/ContactPose.git), or [do it yourself](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)?

Thanks for your patience!

**Comment by akarshkumar0101** [comment]
Merged upstream/master, done!

**Pull request merged**
